### ISSUE TITLE
This app does not work

### ISSUE THREAD

**Issue by tomatkins** [apple/cloudkit-sample-privatedb-sync#2]
Error message: "Error saving new contact: <CKError 0x600003c877b0: \"Bad Container\" (5/1014); \"Couldn\'t get container configuration from the server for container

**Comment by sjrmanning** [comment]
Hi Tom — have you created your own iCloud container and updated both the bundle identifier and container identifier (in Config.swift)? The "Signing & Capabilities" tab in Xcode should tell you if there's a configuration issue.

See [here](https://developer.apple.com/documentation/cloudkit/enabling_cloudkit_in_your_app) for some documentation on enabling CloudKit and configuring a container and bundle ID combination.

**Comment by sanjay-k7r** [comment]
Thanks @sjrmanning  - I think this issue can be closed.
Had the exact same error as tomatkins. But after changing bundleID and using iCloud.<bundleid>, its working.
Created a new bundleID and container as iCloud.<bundleID>
+ Wait 10-15 minutes.
Works!
