### ISSUE TITLE
Should local cache be saved first then save server change token?

### ISSUE THREAD

**Issue by clementinelove** [apple/cloudkit-sample-privatedb-sync#4]
https://github.com/apple/sample-cloudkit-privatedb-sync/blob/d0e8f9cbe76033629def38eeb1f61dc5211405b4/PrivateSync/ViewModel.swift#L81-L85

Hi there, I noticed this sample app saves the server change token before local cache were being saved.
Doesn't this mean if the app exits before local cache saved to the UserDefaults, the app will only fetch changes from the newest token the next time it starts and ignoring all previous changes?

**Comment by sjrmanning** [comment]
Good call — this has been fixed in https://github.com/apple/sample-cloudkit-privatedb-sync/commit/fbd72540261d3270949db6789f324b1bdc805d16. Thanks!
